GET http://localhost:3000/admin/users

############
POST http://localhost:3000/admin/users/regist
content-type: application/json

{
  "user_name":"桐人",
  "password":"123456"
}

############
POST http://localhost:3000/admin/users/login
content-type: application/json

{
  "user_name":"桐人",
  "password":"12345678"
}